### ISSUE TITLE
Question create Error

### ISSUE THREAD

**Issue by KoJaeMin** [KoJaeMin/SearchMyCoding#1]
Question create시 아래와 같은 에러 발생

```terminal
QueryFailedError: insert or update on table "questions" violates foreign key constraint "FK_41568ebdc1afb9aa4299d64e913"
    at QueryFailedError.TypeORMError [as constructor] (/Users/gojaemin/Desktop/project/SearchMyCoding/back/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/gojaemin/Desktop/project/SearchMyCoding/back/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/gojaemin/Desktop/project/SearchMyCoding/back/src/driver/postgres/PostgresQueryRunner.ts:263:19)
    at step (/Users/gojaemin/Desktop/project/SearchMyCoding/back/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/Users/gojaemin/Desktop/project/SearchMyCoding/back/node_modules/tslib/tslib.js:125:57)
    at rejected (/Users/gojaemin/Desktop/project/SearchMyCoding/back/node_modules/tslib/tslib.js:116:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by KoJaeMin** [comment]
Entity 파일에 OneToMany도 추가시 문제 해결
```typescript
    @OneToMany((type) => Question, (question : Question) => question.typeId)
    questions: Question[]
```

<img width="546" alt="스크린샷 2023-01-15 오전 2 02 06" src="https://user-images.githubusercontent.com/77095298/212485429-126ac786-a9a9-480e-aded-777ae5dfcff2.png">


https://github.com/KoJaeMin/SearchMyCoding/blob/f7904dc1e3b41e0295a197405cd9cca22d49a943/back/src/entities/questionTypes.entity.ts#L18

**Comment by KoJaeMin** [comment]
production 환경에서는 yaml 사용하면 좋을 듯 합니다.

https://docs.nestjs.com/techniques/configuration#custom-configuration-files
